#include<stdio.h>
int position=1;

int select_map(position){
switch (position){
    case 2 : found(0); break;
    case 3 : item_drop(); break;
    case 4 : merchant(); break;
    case 5 : found(1); break;
    case 6 : found(2); break;
    case 7 : merchant(); break;
    case 8 : found(8); break;
    case 9 : found(9); break;
    case 10 : found(5); break;
    case 11 : found(6); break;
    case 12 : found(7); break;
    case 13 : merchant(); break;
    case 14 : found(8); break;
    case 15 : merchant(); break;
    case 16 : nothing(); break;
    case 17 : found(9); break;
    case 18 : found(10); break;
    case 19 : merchant(); break;
    case 20 : warp(5); break;
    case 21 : item_drop(); break;
    case 22 : item_drop(); break;
    case 23 : merchant(); break;
    case 24 : found(11); break;
    case 25 : nothing(); break;
    case 26 : merchant(); break;
    case 27 : item_drop(); break;
    case 28 : item_drop(); break;
    case 29 : item_drop(); break;
    case 30 : item_drop(); break;
    case 31 : item_drop(); break;
    case 32 : item_drop(); break;
    case 33 : merchant(); break;
    case 34 : merchant(); break;
    case 35 : merchant(); break;
    case 36 : found(12); break;
    case 37 : found(13); break;
    case 38 : warp(5); break;
    case 39 : item_drop(); break;
    case 40 : item_drop(); break;
    case 41 : merchant(); break;
    case 42 : item_drop(); break;
    case 43 : nothing(); break;
    case 44 : item_drop(); break;
    case 45 : item_drop(); break;
    case 46 : item_drop(); break;
    case 47 : item_drop(); break;
    case 48 : merchant(); break;
    case 49 : item_drop(); break;
    case 50 : item_drop(); break;
    case 51 : item_drop(); break;
    case 52 : merchant(); break;
    case 53 : merchant(); break;
    case 54 : found(14); break;
    case 55 : found(15); break;
    case 56 : found(16); break;
    case 57 : item_drop(); break;
    case 58 : merchant(); break;
    case 59 : found(17); break;
    case 60 : warp(5); break;
    case 61 : item_drop(); break;
    case 62 : item_drop(); break;
    case 63 : merchant(); break;
    case 64 : item_drop(); break;
    case 65 : nothing(); break;
    case 66 : item_drop(); break;
    case 67 : item_drop(); break;
    case 68 : item_drop(); break;
    case 69 : item_drop(); break;
    case 70 : merchant(); break;
    case 71 : item_drop(); break;
    case 72 : item_drop(); break;
    case 73 : item_drop(); break;
    case 74 : item_drop(); break;
    case 75 : found(18); break;
    case 76 : merchant(); break;
    case 77 : item_drop(); break;
    case 78 : found(19); break;
    case 79 : item_drop(); break;
    case 80 : item_drop(); break;
    case 81 : item_drop(); break;
    case 82 : item_drop(); break;
    case 83 : found(20); break;
    case 84 : item_drop(); break;
    case 85 : found(21); break;
    case 86 : found(22); break;
    case 87 : found(23); break;
    case 88 : found(24); break;
    case 89 : item_drop(); break;
    case 90 : item_drop(); break;
    case 91 : merchant(); break;
    case 92 : found(25); break;
    case 93 : item_drop(); break;
    case 94 : merchant(); break;
    case 95 : merchant(); boss(1); break;
    case 96 : merchant(); boss(1); break;
    case 97 : merchant(); boss(1); break;
    case 98 : merchant(); boss(1); break;
    case 99 : merchant(); boss(1); break;
    case 100 : merchant();boss(1); break;
}
}
void item_drop(int gold,int equip_hp,int equip_atk){

}
